Repository amosproj/amos-ss2021-emba-service, pull requests merged in 2021-05, with the labels that each got.

#47 Add sql setup
  .env
  .gitignore
  Dockerfile
  docker-compose.yml
  embark/embark/settings.py
  embark/requirements.txt
Labels: backend, enhancement

#53 Update docker setup
  Dockerfile
  docker-compose.yml
  embark/entrypoint.sh
Labels: backend

#66 Update docs and URLs
  docker-compose.yml
  docker.md
  embark/embark/urls.py
  template.env
Labels: backend, documentation

#65 fix path of installer.sh in dockerfile
  Dockerfile
Labels: backend, bug

#74 Bounded executor
  embark/uploader/__init__.py
  embark/uploader/boundedExecutor.py
  embark/uploader/run_bounded_exec.py
  embark/uploader/test.py
  embark/uploader/test_boundedExecutor.py
  embark/uploader/urls.py
  embark/uploader/views.py
  setup.cfg
Labels: backend
